### ISSUE TITLE
C# generics are rendered incorrectly

### ISSUE THREAD

**Issue by ugumba** [oleg-shilo/DocPreview.VSIX#1]
Hi, great extension!
C# generics fail to render correctly.  For example, the method
`public static Task<Output<ChunkedVolume<T>>> CreateChunkedVolumeFromVolumeSpec<T>(Output<VolumeSpec> volumeSpec, [SpawnId] ChunkingConstraints constraints, Out<Output<Chunking>> chunking, IFlowsContext context)`
is rendered as
`
public static Task>> CreateChunkedVolumeFromVolumeSpec(Output volumeSpec, [SpawnId] ChunkingConstraints constraints, Out> chunking, IFlowsContext context)
`

**Comment by oleg-shilo** [comment]
Tank you.
Will have a look at it.

**Comment by oleg-shilo** [comment]
Done.
Please update the extension.
