### ISSUE TITLE
Add support for <value>

### ISSUE THREAD

**Issue by GeorgKrichel** [oleg-shilo/DocPreview.VSIX#11]
"Using DocView" says:
 DocPreview supports all recommended documentation tags except , which is not a subject of preview.
 At
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments
&lt;value&gt; is listed.
 DocView does yet not Support &lt;value&gt;.

**Comment by GeorgKrichel** [comment]
Sorry, didn't know about Problems displaying &lt; and &gt;. Text should read as follows:

"Using DocView" says:
 DocPreview supports all recommended documentation tags except , which is not a subject of preview.
 At
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments
&lt;value&gt; is listed.
 DocView does yet not Support &lt;value&gt;.

**Comment by oleg-shilo** [comment]
Planned for implementation. Txs

**Comment by oleg-shilo** [comment]
Implemented in v1.3.7.0
