### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by lf-** [oleg-shilo/DocPreview.VSIX#12]
Currently, the extension doesn't do anything when the refresh button is pressed in an F# document. This appears to suggest that F# isn't supported.

From what I've seen, NRefactory is maintainerless and lacks F# support so this may be a difficult thing to add.

**Comment by oleg-shilo** [comment]
I have dropped NRefactory as it conflicts with Xamarin VS runtime. Thus extending support to F# should not be that difficult.

Please send me an example of F# inline xml doc and will work on it.

**Comment by lf-** [comment]
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation#code

It's the same as C#.

**Comment by oleg-shilo** [comment]
Done. 
Please update to the latest v1.3.8.0 release.
