### ISSUE TITLE
Incorrect syntax section generated for enum value

### ISSUE THREAD

**Issue by jramos-br** [oleg-shilo/DocPreview.VSIX#14]
Hello. I'm trying to preview the documentation for the enum values and something is going wrong in the Syntax section. Intellisense displays the correct content and I'm not seeing anything wong with the XML. Image attached. Windows 10 1909, VS2017 15.9.18 and DocPreview 1.3.8. Image below.

![Annotation 2020-01-05 181457](https://user-images.githubusercontent.com/543648/71786215-ba6edd00-2fe7-11ea-8a49-f32a6e55ed65.png)

**Comment by oleg-shilo** [comment]
Seems like a defect. Will work on it. 
Thank you for reporting.

**Comment by oleg-shilo** [comment]
Just released the fix: v1.3.9.0
