### ISSUE TITLE
User CSS support

### ISSUE THREAD

**Issue by HTD** [oleg-shilo/DocPreview.VSIX#16]
It would be a nice feature, if a user could provide own custom CSS for the documentation. Or is it already possible?

**Comment by oleg-shilo** [comment]
Yes it is possible. I made this issue into a feature request.

**Comment by oleg-shilo** [comment]
Done. Will publish in a day or two.
![image](https://user-images.githubusercontent.com/16729806/92301755-9f56d180-efa9-11ea-9dff-a1cb18458735.png)

**Comment by HTD** [comment]
The problem is in HTML, barely fixable with CSS. BTW, the CSS is to be rewritten too. I could fix that (starting with the HTML template), where can I find it? Could you point me to the appropriate source file? (HTML: insane structure, unmatched tags, content within header - and that are only things I found in 1st minute of reading, CSS: all values in pixels and points which is terribly bad for scaling, every part of the document absolutely positioned, defeating the very point of most HTML and CSS features, instead of using paddings and margins, workarounds to fix workarounds around workarounds, crazy IE hacks irrelevant for a good 10 years, and again - this is first minute of reading, good CSS with the theme would be 10 times shorter and simpler, the theme alone (colors) should have like 10 LOC, I mean - it really need to be replaced). My time is very limited lately, so if you would point me the files to fix, it would be just great, I could make it right in no time.
