### ISSUE TITLE
Is there a VSIX build for VS 2022? Thanks

### ISSUE THREAD

**Issue by reponemec** [oleg-shilo/DocPreview.VSIX#18]

**Comment by oleg-shilo** [comment]
Not yet, but it is the very next activity that I need to do.
Unfortunately with VS2022 MS has changed (again) extension hosting API and I need to recreate, rebuild and republish all my extensions.

It will be done within a week or so

**Comment by reponemec** [comment]
Excellent, thank you.

**Comment by oleg-shilo** [comment]
Done.
Please update via VS
