### ISSUE TITLE
Not working with <example><code> tag

### ISSUE THREAD

**Issue by joymon** [oleg-shilo/DocPreview.VSIX#3]
When I add the example code snippet, the preview breaks and not even showing the other things such as summary, param etc...

**Comment by oleg-shilo** [comment]
The preview works only for the well formatted XML doc content. This is the purpose of this extension - to catch the cases when the XML doc content is broken.

Thus if you doesn't see the preview being rendered as expected it means that there is an error in the XML.

Below is the example of the well formatted `<example>` tag:

``` C#
/// <summary>
/// Defines Event source for windows Event Log service.
/// </summary>
/// <seealso cref="WixSharp.WixEntity" />
/// <seealso cref="WixSharp.IGenericEntity" />
/// <example>The following is an example of creating a shortcut to the Wix# website.
/// <code>
/// var project =
/// new Project("MyProduct",
///     new Dir(@"%ProgramFiles64Folder%\My Company\My Product",
///        new InternetShortcut
///        {
///            Name = "My Online Documentation",
///            Target = "https://github.com/oleg-shilo/wixsharp"
///        },
///         ...
///
/// project.BuildMsi();
/// </code>
/// </example>
public class InternetShortcut : WixEntity, IGenericEntity
{
. . .
```
And this is how it is rendered in the preview window:

![image](https://user-images.githubusercontent.com/16729806/44770206-a4a70780-abaa-11e8-89cb-f143e36dc866.png)

**Comment by Novack** [comment]
I found problems rendering the preview if the summary or the params (and I guess any other potential section) have the ampersand character ('&'), so if comes to parsing issues, I would start looking for special characters like that one.

**Comment by oleg-shilo** [comment]
A am not sure it is the case. The ampersand documentation content is rendered as expected:

![image](https://user-images.githubusercontent.com/16729806/51437890-6bf20100-1cf8-11e9-8bde-1632d5ae7514.png)

I assume you escape it as you should.

**Comment by Novack** [comment]
I was not using `&amp;` but simply using "&" (in my case I was not planning to export the xml docs when created the comments). Simply having that character on a comment, would break the parsing for me, at one spot it was on a summary tag, and another on a param tag.

**Comment by oleg-shilo** [comment]
Yep, this is what I expected.

The XML doc comment must be a 100% valid XML. The whole purpose of this extension is just to do two things:
- detect when XML becomes broken
- preview XML->HTML conversion and rendering to ensure it is readable and serves the purpose 

Thus if one is placing any illegal XML characters that are not tags (e.g. `<`, `>`, `&`) then conversion/rendering is broken.
