### ISSUE TITLE
<paramref> not shown when in <exception>

### ISSUE THREAD

**Issue by cdonnellytx** [oleg-shilo/DocPreview.VSIX#4]
The following code example doesn't generate HTML for the `paramref` tag:

```xml
        /// <exception cref="T:System.ArgumentNullException">The <paramref name="innerException"/> argument
        /// is null.</exception>
```

Expected:
```
<tr>
<td><span class='PseudoLink'>System.ArgumentNullException</span></td>
<td>The <span class="Code">innerException</span> argument
 is null.</td>
</tr>
```

Actual:
```html
<tr>
<td><span class='PseudoLink'>System.ArgumentNullException</span></td>
<td>The  argument
 is null.</td>
</tr>
```

![image](https://user-images.githubusercontent.com/183046/45453130-8a3e5500-b6a5-11e8-8fcd-d4355858392f.png)

Microsoft is using this pattern [here](https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception.-ctor?view=netframework-4.7.2#System_AggregateException__ctor_System_String_System_Exception_):
![image](https://user-images.githubusercontent.com/183046/45453454-747d5f80-b6a6-11e8-9d64-2e80d5cc03e7.png)

Let me know if there's any more info you need from me, or if I can help in any way.

Thanks for making a great tool!

\# Chris

**Comment by oleg-shilo** [comment]
Thank you. I am sincerely glad you like DocPreview.
 Yes it is a defect. I have just published the fix (v.3.1.0): https://marketplace.visualstudio.com/items?itemName=OlegShilo.DocPreview
