### ISSUE TITLE
VB.NET and syntax paragraph

### ISSUE THREAD

**Issue by EdwardLyle** [oleg-shilo/DocPreview.VSIX#5]
In VB.NET DocPreview returns the hole source code for syntax because DocPreview is searching for C#‘s {}.
Is it possible to fix that? :-)

**Comment by oleg-shilo** [comment]
Thank you for reporting. Will fix with the next opportunity.

**Comment by oleg-shilo** [comment]
Fixed in v1.3.2.0

**Comment by EdwardLyle** [comment]
Works like a charme. 👍
