### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by EdwardLyle** [oleg-shilo/DocPreview.VSIX#7]
Is it possible to add a dark mode Preview?

**Comment by oleg-shilo** [comment]
Not exactly. The theme (css) of the preview is matching the theme produced by SandCastle and as such it show you the final outcome of help file content as it is going to be displayed when you open chm file.

Saying that, you can adjust your local copy of the css to achieve any desired style.

- Right-click the preview content and select view source.
- In the content find the location of the css file(s). 

Now you can modify it to suit your needs.

If you like, you can share your theme here and I can include it in the distro as an alternative style option.

**Comment by EdwardLyle** [comment]
Here is my css file for a dark mode theme. :)
[Contents.css.txt](https://github.com/oleg-shilo/DocPreview.VSIX/files/2575776/Contents.css.txt)

**Comment by oleg-shilo** [comment]
Done. Update from the extension manager.

![image](https://user-images.githubusercontent.com/16729806/48413346-8c9f5700-e79b-11e8-8837-a578b9581db1.png)
